name: Windows

on:
  push:
    branches: [ master, ci ]
    tags: ['v*']
  pull_request:
    branches: [ master, ci ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          # Windows2019 & VS 2019 supports 11.0+
#          - os: windows-2019
#            visual_studio: "Visual Studio 16 2019"
#            python-version: "3.8"
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
            python-version: "3.11"
    env:
      build_dir: "build"
      config: "Release"

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: CMake version
      shell: bash
      run: cmake --version

    - name: Install Conan
      shell: bash
      run: |
        pip install -U conan
        echo 'tools.system.package_manager:mode=install' > global.conf
        conan config install global.conf

    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
        sub-packages: '["nvcc", "cudart", "cublas", "visual_studio_integration"]'

    - name: nvcc check
      shell: powershell
      run: |
        nvcc -V
        ls $env:CUDA_PATH
        ls $env:CUDA_PATH\bin
        ls $env:CUDA_PATH\include

    - name: Configure CMake
      id: configure
      shell: bash
      run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Configure Error Processing
      if: ${{ (failure() && steps.configure.outcome == 'failure') || success() }}
      working-directory: ${{ env.build_dir }}
      shell: bash
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi

    - name: Build
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --config ${{ env.config }} --target ALL_BUILD --verbose

    - name: Build package
      working-directory: ${{ env.build_dir }}
      run: |
          python -m pip install -U pip wheel setuptools
          cmake --build . --config ${{ env.config }} --target pip-package --verbose

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      working-directory: ${{ env.build_dir }}/lib/python_package
      env:
        PYPI_USERNAME: ${{ secrets.pypi_username }}
        PYPI_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python -m pip install twine
        python -m twine upload -u $env:PYPI_USERNAME -p $env:PYPI_PASSWORD pip_package/*